### PR TITLE
refactor: Uses standard org.sonar.check.Rule annotation

### PR DESCRIPTION
**Pull request by jycr**
fix: #15

### CODE REVIEW

**Comment by dedece35** [comment]
Hi @jycr,
before all, could you correct the build / test errors please ?

**Comment by jycr** [comment]
> Hi @jycr, before all, could you correct the build / test errors please ?

I don't think this SonarCloud analysis is a problem of my PR, but a problem in repo configuration? Isn't it?

> Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project ios-plugin: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project ios-plugin: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator

**Review by zippy1978 — CHANGES_REQUESTED** [review]
See comments

**Comment by zippy1978** [comment]
Hi @dedece35 , @jycr,
As I need to merge this refact soon, I did address the comments of this one and issued a new PR here : https://github.com/green-code-initiative/ecoCode-ios/pull/20

So you can close this one, and review the new one instead.

**Comment by dedece35** [comment]
Hi @zippy1978,
as you wanted, PR closed.

**Pull request closed without merging**
